### ISSUE TITLE
discordClient may be undefined at some places where it is used

### ISSUE THREAD

**Issue by Blatoy** [forwards-long-jump/discotron#7]
Make sure the bot is able to start even when Discord is down

**Comment by RedMser** [comment]
The following proposal would solve the issues of discordClient being undefined, discordClient timing out unexpectedly when discord is dead but logged in, and it will allow mocking discordClient for tests.

We can have something called a `ClientProvider` (todo work on name). For the caller, it looks like this:
```js
// Before
const guild = global.discordClient.guilds.get(discordGuildId);

// After
const guild = ClientProvider.get().guilds.get(discordGuildId);
```
It would still give you the familiar DiscordJS API, but with some additional functionality:
- We can detect if we did not login to Discord (checked only when calling `.get()`), and throw an error instead of providing you with undefined and expecting the programmer to handle this case everywhere.
- We can detect if Discord is down (checked only when calling `.get()`), and throw an error instead of providing you with a client instance. This way, we don't have to wait for the API call to timeout. But we still should (in the background) check for Discord's status, so we would reconnect even without trying to query the API explicitly here.
- For unit tests, we can return a mock version of the DiscordJS API which can either return fake data or act as if certain error conditions are present (id not found, etc).
